{{- if and .Values.admission.tlsSecret.create (eq .Values.admission.tlsSecret.create true) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "excatadmission.tlsSecretName" . }}
  labels:
    {{- if .Values.admission.labels }}
    {{- toYaml .Values.admission.labels | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.admission.tlsSecret.certFileName | b64enc }}
  tls.key: {{ .Files.Get .Values.admission.tlsSecret.keyFileName | b64enc }}
{{- end }}