{{- if .Values.admission.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "excat-admission.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.admission.labels }}
    {{- toYaml .Values.admission.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.admission.annotations }}
  annotations:
    {{- toYaml .Values.admission.annotations | nindent 4 }}
  {{- end }}
{{- end }}