{{- if .Values.devicePlugin.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "excat.fullname" . }}-deviceplugin
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "excat.fullname" . }}-deviceplugin
subjects:
  - kind: ServiceAccount
    name: {{ include "excat.devicePlugin.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
