{{- if .Values.devicePlugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "excat.devicePlugin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.devicePlugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.devicePlugin.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
