name: action lint
on:
  push:
    branches:
      - main
  pull_request:
permissions: read-all
jobs:
  actionlint:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: "{extends: relaxed}"
          file_or_dir: .github/
