name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Check dependency licenses
        shell: bash
        run: |
          go install github.com/uw-labs/lichen@latest
          lichen --config=.github/config/lichen_config.yaml \
            build/admission build/deviceplugin | tee lichen.txt
      - name: Upload license scan result
        uses: actions/upload-artifact@v4
        with:
          name: License list
          path: lichen.txt
